version: '3'

services:
  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www:rw
      - ./logs:/var/log:rw
    depends_on:
      - mysql
      - redis

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - web
    ports:
      - 8910:80 # <project port>:80 (http://127.0.0.1:80)

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - 3308:3308

  redis:
    image: redis:alpine

  adminer:
    image: adminer
    depends_on:
      - web
      - mysql
    ports:
      - 8080:8080
